#!/usr/bin/env python3
from pathlib import Path
import sys
sys.path.insert(0,str(Path(__file__).resolve().parent))
from blackboard_remote import helper
try:
    helper()
except Exception as error:
    print('Blackboard Git: '+str(error),file=sys.stderr)
    sys.exit(1)
